name: Terraform Deploy
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: devops

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials ü§ñ
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Setup Terraform üåç
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        working-directory: infrastructure
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TFSTATE_BUCKET }}" \
            -backend-config="key=${{ vars.TFSTATE_KEY }}"

      - name: Terraform Plan
        working-directory: infrastructure
        run: |
          terraform plan -out=tfplan \
            -var 'bucket_name=${{ vars.STORAGE_BUCKET }}'


      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply tfplan
