name: Terraform Destroy
on: workflow_dispatch

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: devops

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials ğŸ¤–
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Terraform ğŸŒ
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init ğŸš€
        working-directory: infrastructure
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TFSTATE_BUCKET }}" \
            -backend-config="key=${{ vars.TFSTATE_KEY }}"

      - name: Terraform Destroy ğŸ’€
        working-directory: infrastructure
        env:
          TF_VAR_bucket_name: ${{ vars.STORAGE_BUCKET }}
          TF_VAR_cluster_name: ${{ vars.ECS_CLUSTER }}
          TF_VAR_ecr_repo_name: event-management-system
          TF_VAR_db-password: ${{ secrets.DB_PASSWORD }}
        run: terraform destroy -auto-approve